services:

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: [".env", ".env.local"]

  adminer:
    depends_on:
      - db
    ports:
      - "8080:8080"
    image: adminer:latest
    restart: unless-stopped

volumes:
  postgres_data: