import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { getCampaigns } from "@/access-providers/patreon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()

  if (session?.user?.id) {
    await getCampaigns(session.user.id).then((campaigns) => {
      console.log(JSON.stringify(campaigns, null, 2));
    });
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
